### ISSUE TITLE
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: nick-fields/persist-action-data@v1.1

### ISSUE THREAD

**Issue by sumedh-ikea** [nick-invision/persist-action-data#6]
We are getting WARNING as Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: nick-fields/persist-action-data@v1.1. Node 12 has been out of support since April 2022. Is it possible to update current plugin based on Node.js 16 dependencies.

**Comment by nick-fields** [comment]
Thanks for reporting, I forget this action exists. This was fixed by #7. I just bumped the runtime to `node16` and updated the `@actions/*` dependencies to latest.

**Comment by sumedh-ikea** [comment]
Thanks @nick-fields for quick response
